version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: biblioteca-app
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - database
      - redis

  database:
    build: .docker/postgres
    container_name: biblioteca-db
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=biblioteca-backend
      - POSTGRES_DB=biblioteca-backend

  redis:
    image: 'bitnami/redis:lastest-alpine'
    container_name: biblioteca-redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes